### ISSUE TITLE
renaming dsound

### ISSUE THREAD

**Issue by wolfrunner86** [drdaxxy/gta5fov#1]
when i change the dsound.dll and the spot in the ini it still wont load. i have tried leaving it as dsound and it is working for me that way, but i need to use a different dsound for another mod.

**Comment by ImNotAHacker7828** [comment]
i am having the same issue -_-

**Comment by drdaxxy** [comment]
Works exactly as intended.

Here's what you do if you want to use both the FoV mod and ASI loader:
- Install the FoV mod as normal.
- Install ASI loader's dsound.dll but rename it to, for example, asiloader.dll
- Open fov.ini
- Uncomment the "ProxyLibrary" line (remove the semicolon at the start of it) and change "other_dsound.dll" to "asiloader.dll"
- Save fov.ini

The crucial part here is that the file named dsound.dll in your GTA folder should still be the FoV mod. The other mod needs to have a different name. That doesn't have to be asiloader.dll, of course, you can use whatever name you want, but you'll need to adjust the ProxyLibrary parameter in fov.ini accordingly.

**Comment by wolfrunner86** [comment]
ok it was not clear in the text files that you had to change the other mods dsound and not the one that came with FOV, it works perfectly now thanks for the quick reply and the GREAT mod
