### ISSUE TITLE
gta5fov broken again

### ISSUE THREAD

**Issue by PhunkMaZ** [drdaxxy/gta5fov#10]
Hi DrDaxxy, today's patch has broken the mod again. Looks like they've changed too much in their binaries.

Cheers,
PhunkMaZ

**Comment by ghost** [comment]
Changed too much?

**Comment by drdaxxy** [comment]
I'll look at this tomorrow, thanks.

**Comment by drdaxxy** [comment]
To anyone who was watching this issue, I just released version 1.32 on here (other sites following soon) which is compatible with the latest patch.

**Comment by ghost** [comment]
You guys fucking rock!

**Comment by TomFetti** [comment]
Had to sign-up to say Thank you daxxy!! been watching this for the last two days. Cheers!!!
