### ISSUE TITLE
Bikers DLC Patch has broken FOV-Mod again

### ISSUE THREAD

**Issue by PhunkMaZ** [drdaxxy/gta5fov#13]
Hi drdaxxy, todays content-patch has broken the mod again. Game stops working at the intro/credits screen. Hope you can update the mod.

Cheers,
Mathias

**Comment by drdaxxy** [comment]
I've heard about this from a number of people.
Don't have time to work on it right now, but I'll take care of it in a couple days.

**Comment by PhunkMaZ** [comment]
Wonderful, thank you :)

**Comment by PCPisChill** [comment]
firstPersonWalkingPatch is what's causing the crash for me.

**Comment by TheArtOfTrading** [comment]
Thanks in advance drdaxxy, you're a legend! The game is downright unplayable for me in first person without your mod.

**Comment by imthatgin** [comment]
How do you find the specific signatures? Maybe it's something the community could do when you don't have the time to do so?

**Comment by PCPisChill** [comment]
@ryan-kingstone https://github.com/drdaxxy/gta5fov/blob/59b754108e847801ece153fa720a4e6e13bc3e36/GTA5FoV/patches.h#L35

If you comment out firstPersonWalkingPatch everything else seems to work fine. It looks like the game instruction being modified: mov eax,[rsi+000013C0] was updated to mov eax,[rsi+000013E8] in the bikers update, but changing 0xC0 to 0xE8 in firstPersonWalkingCode doesn't fix the problem.

**Comment by drdaxxy** [comment]
@PCPisChill Thanks for checking this out for me. I'll see what I can do about this later tonight.

After fixing the immediate issue I might take a look at the game again in a while and see if I can't whip up something more robust to updates.

**Comment by drdaxxy** [comment]
Alright, it's fixed.

@PCPisChill That was indeed the problem. You probably forgot to adjust the signature in addition to the injected code.

**Comment by PhunkMaZ** [comment]
Thanks a million!
