### ISSUE TITLE
Not working on 1.42 (Doomsday Heist Update 1.0.1290.1)

### ISSUE THREAD

**Issue by raf555** [drdaxxy/gta5fov#17]
the FoV mod makes the game crash on the doomsday update.
Please update the mod to the new version of the game

**Comment by Jitnaught** [comment]
Hasn't been working since 1.0.1011.1 (I think that's the correct version) actually.

**Comment by raf555** [comment]
@Jitnaught but before the doomsday update, this mod worked fine on my game. I tried scripthook and original version, both of them arenot working on the new update.

**Comment by Jitnaught** [comment]
Were you running on an old version (944 or below)? 944 is the last version that the mod's been updated for I believe.

**Comment by raf555** [comment]
@Jitnaught no, i always update my game when the new update arrived. It doesnt work only after doomsday update.

**Comment by PCPisChill** [comment]
firstPersonCrouchingSignature needs to be updated for 1290
https://github.com/drdaxxy/gta5fov/blob/59b754108e847801ece153fa720a4e6e13bc3e36/GTA5FoV/patches.h#L150

Going to the place where the signature was in ida, the sigged instruction no longer exists:
![firstpersoncrouchingsignature](https://user-images.githubusercontent.com/22227370/34153247-419877a2-e466-11e7-89e9-9dc21441a5f1.png)

Commenting the patches out will fix the crash, but then when you crouch in first person it sets the fov back to normal

**Comment by drdaxxy** [comment]
Thanks for the heads up (and the analysis @PCPisChill ), I'll take care of this when I have time (hopefully tonight).

I swear, one of these days I'm gonna replace this with something more robust...

**Comment by raf555** [comment]
@drdaxxy thanks for your work!

**Comment by drdaxxy** [comment]
Fix is up on here, see Releases ( https://github.com/drdaxxy/gta5fov/releases/tag/1.35 ). Pushing to Nexus and 5mods now-ish.
