### ISSUE TITLE
CTD after latest patch

### ISSUE THREAD

**Issue by PhunkMaZ** [drdaxxy/gta5fov#6]
Hi DrDaxxy, after todays DLC release GTAV crashes while displaying the intro/legal info. Hope there's something you can do to get this fantastic mod working again :)

Cheers

**Comment by drdaxxy** [comment]
Noted. I was just about to go to bed, so I'll patch this tomorrow.

**Comment by ghost** [comment]
Thanks man! I came here to report this same issue

**Comment by PhunkMaZ** [comment]
Thank you for looking into the problem! I can't touch GTA with this essential mod ;)
