### ISSUE TITLE
Incompatibility with Rage Plugin Hook; causes CTD on start when both are installed.

### ISSUE THREAD

**Issue by EvilJackCarver** [drdaxxy/gta5fov#8]
Version 1.31 is incompatible with the Rage Plugin Hook which is packaged with the LSPD First Response modification that came out June 19. When the dsound.dll is inside the root GTA archive, the game will load, however if I start it via RageHook or start RageHook after the game is already running, the game will crash to desktop. I have tried running both with elevated privileges. 

~~I am uncertain of the version of the Rage Plugin Hook that is being used.~~ I just updated RageHook to 0.12.535.2412 and can confirm it is still causing the CTD on startup.

Besides the above-mentioned modifications, my game is running unmodified, patch 1.0.372.2.

If needed, I can get a recursive directory output of my root GTA directory. RageHook does not generate a logfile.

**Comment by drdaxxy** [comment]
Thanks, I'll look into this.

**Comment by drdaxxy** [comment]
Sorry for the delay. Just tried the latest version of LSPD-FR (0.1e) with the bundled version of RagePluginHook (0.14.546.2543) and I can't reproduce this issue. Please try updating and tell me if this still happens.

**Comment by EvilJackCarver** [comment]
I didn't even notice LSPDFR had updated - seems to be working fine now.
